Move Rest of DLC imports into make functions
datajoint/element-deeplabcut pull request #72
Opened 2023-01-13 01:21 UTC by sidhulyalkar

- CUDA issues between torch package required by certain steps in DLC are still occurring. 
- Currently solution is to move all imports into the make functions while they are used. This will allow for importing of workflow.pipeline in the Sabatini ephys (spike-sorting-worker), which requires a different CUDA version(11.0.3) than is required by DLC(11.2).

2023-01-13 18:02 UTC, CBroz1 commented
After discussion, marking as draft pending further testing, rather than iterating on the main fork

2023-01-17 16:15 UTC, ttngu207 approved these changes

2023-01-17 18:44 UTC, CBroz1 submitted a review, later dismissed

2023-01-17 19:19 UTC, sidhulyalkar commented
> Thanks for confirming these work, @sidhulyalkar. Please add notes to the changelog to reflect this lazy import adjustment. Do you plan to make a new release? If so, please also version bump and plan to tag once merged

Updated the changelog and the version, I can push the tag and make a new release after this is merged

2023-01-17 19:30 UTC, CBroz1 requested changes

2023-01-17 19:30 UTC, CBroz1 commented on CHANGELOG.md
> ++ Update - adjusted DLC related imports to be lazy
```suggestion
+ Update - Adopt lazy import strategy for imported DeepLabCut functions
```

2023-01-17 19:57 UTC, CBroz1 approved these changes

2023-01-17 19:57 UTC, merged