Merge workflow-deeplabcut's tutorial environment
datajoint/element-deeplabcut pull request #89
Opened 2023-09-28 23:05 UTC by MilagrosMarin

2023-09-28 23:08 UTC, kushalbakshi commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: https://datajoint.com/docs/community/contribute/
```suggestion
    url: https://datajoint.com/docs/about/contribute/
```

2023-10-02 22:41 UTC, kushalbakshi requested changes
Looks good! Just a few small things.

2023-10-02 22:41 UTC, kushalbakshi commented on setup.py
> +    description="DeepLabCut DataJoint Element",
```suggestion
    description="DataJoint Element for Continuous Behavior Tracking via DeepLabCut",
```

2023-10-02 22:41 UTC, kushalbakshi commented on setup.py
> +    keywords="neuroscience behavior pose-estimation science datajoint",
```suggestion
    keywords="neuroscience behavior deeplabcut pose-estimation science datajoint",
```
Let's leave deeplabcut in there

2023-10-02 22:41 UTC, kushalbakshi commented on setup.py
> +            "element-interface>=0.5.0",
```suggestion
            "element-lab>=0.3.0",
            "element-animal>=0.1.8",
            "element-session>=0.1.5",
            "element-interface>=0.6.0",
```

2023-10-03 12:12 UTC, MilagrosMarin reviewed
I have accepted your suggestions, @kushalbakshi . Thank you!

2023-10-03 15:24 UTC, kushalbakshi approved these changes

2023-10-03 16:13 UTC, kushalbakshi commented
Let's wait on the `Black` formatting until we are ready to merge this into the `main` branch. I was able to build a Codespace without any issues so I'll proceed with merging. Thanks for your work on this @MilagrosMarin

2023-10-03 16:14 UTC, merged